### ISSUE TITLE
Bridge Program Checklist Issue: WIP Example

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/EBR-Tools-Training#6]
### :octocat: : GitHub Bridge Program
Welcome to the GitHub Bridge Program for Sales Development! We know it's a lot of information so we've strategically structured this training program to build on the fundamental sales skills obtained in Sales Development. The five sessions below are built to provide classroom, written and tactical training for roles including but not limited to Corporate Sales, Field Sales, and Account Management.  

### 📁 Prerequisites:  
  - Sales Development Representative must have completed their ramp period and have retired quota for two rolling months. 
  - Current Corporate Sales Representatives and Account Managers are eligible to participate in refresh and enhance their current skills.  
  - Representatives cannot participate in months with 5+ vacation days. 
### :apple: Objectives:  
  - Training Sales Development Representatives in areas need to be successful in roles such as Corporate Sales Representative and Account Manager. This is done by combining classroom presentations from rep[resentatives currently in the roles, tactical/technical projects for hands-on experience and roleplays to enhance soft sales skills. 
  - Providing ongoing training for current Corporate Sales Representative and Account Managers. 
  - Each session will run for one month on a rolling basis. Representatives should be able to drop into the program at any time during the rolling sessions. Completing the full program should take five months if no breaks are taken.  
- [ ] **Pre-work**: 
   - Work with current session leader to pick one deal to work as an example throughout the program.

## :white_check_mark: Discovery & Evaluation Planning
- [ ] **Classrom Presentation**
- [ ] **Observe**: Listen to Mock Discovery Call 
- [ ] **Activity**: Build an Evaluation Plan 
  - **LINK EVAL PLAN HERE**
- [ ] **Presentation & Feedback**: Schedule time with session leader to review and receive feedback
  - [ ] Session leader approves Evaluation Plan  
## :white_check_mark: Pitch & Initial Proposals 
- [ ] **Classrom Presentation**
- [ ] **Activity**: Create Pich & Proposal 
  - **LINK PITCH & PROPORSAL HERE**
- [ ] **Presentation & Feedback**: Schedule time with session leader to do a mock pitch & present proposal. 
## :white_check_mark: Forecasting
- [ ] **Classrom Presentation**
- [ ] **Observe**: Attend a Forecast call of Corporate Sales or Account Management
- [ ] **Activity**: Schedule time with the session leader to build a forecast report in SFDC. (depending on the sessions size, session leader may scheudle this as a group)
  - **LINK SFDC REPORT HERE**
- [ ] **Observe/Activity**: Schedule time with the session leader to observe an individual deal forecast. Follow along and create your own report using this template. (depending on the sessions size, session leader may schedule this as a group)
  - **LINK DEAL FORECASTED DEAL HERE**
- [ ] **Presentation & Feedback**:  Session leader will review the submitted documents and provide feedback async. 
## :white_check_mark: Mapping & Miscellaneous 
- [ ] **Classrom Presentation**: Personas, Org Charts, Identifying Pitfalls 
- [ ] **Activity**: Create an Org Chart 
  - **LINK ORG CHART**
- [ ] **Presentation & Feedback**: Group schedules time with session leader to review org charts for feedback and questions.
## :white_check_mark: Negotiations & Second-Round Proposals 
- [ ] **Classrom Presentation**
- [ ] **Observe/Activity**: Listen to mock call 
- [ ] **Activity**: Write second proposal
  - **LINK SECOND PROPOSAL HERE**
